spring:
  datasource:
    url: "jdbc:oracle:thin:@connectiontest_high?TNS_ADMIN=/home/jhordycg/wallet"
    username: "ADMIN"
    password: "DBVEbrVykZ2e7cr"
    driver-class-name: "oracle.jdbc.OracleDriver"
    hikari:
      read-only: "false"
  jpa:
    hibernate:
      ddl-auto: "create"
      use-new-id-generator-mappings: "true"
    generate-ddl: "true"
server:
  servlet:
    context-path: "/api"