spring:
  datasource:
    url: "jdbc:oracle:thin:@connectiontest_high?TNS_ADMIN=/home/jhordycg/wallet"
    username: "ADMIN"
    password: "DBVEbrVykZ2e7cr"
    driver-class-name: "oracle.jdbc.OracleDriver"
  jpa:
    hibernate:
      ddl-auto: "create"
server:
  servlet:
    context-path: "/api"